### ISSUE TITLE
Work on writing the ld format (From CSV)

### ISSUE THREAD

**Issue by LDwhoRU** [gotzl/ldparser#1]
Are you interested in writing the format in inverse? I'm working on using this parser to write a pandas dataframe into a MoTeC file, so you can use MoTeC to analyse data off of any logger. Can the project be expanded to include this?

**Comment by gotzl** [comment]
Hi, somehow missed this comment... But, yes this should be doable. There are some unknowns in the data format, though... It has to be seen what has to be done for MoTeC to accept the data. I'll look into it ;)

**Comment by LDwhoRU** [comment]
> Hi, somehow missed this comment... But, yes this should be doable. There are some unknowns in the data format, though... It has to be seen what has to be done for MoTeC to accept the data. I'll look into it ;)

Sweet! Do you have Discord or some other contact reference I can reach out to you on? I spent a few weeks looking at your code trying to reverse engineer it, but to no avail (Largely due to the headers you have to write). 

If you have discord, my tag is LDwhoRU#6938. Otherwise let me know where else I can contact you, I'd love to work on this with you.

**Comment by gotzl** [comment]
I've already started on this - or at least did some prerequisites. It's now possible to read and write files. However, what's still missing is to generate valid headers for eg a pandas DataFrame. I've yet to think this through.
(Also note, so far I've only tested everything with files generated by AssettoCorsa Competizione...)

**Comment by davimarriel** [comment]
Did you have the code to convert CSV to LD files complete already?
