### ISSUE TITLE
UnicodeDecodeError and Datatype 5 not recognised. 

### ISSUE THREAD

**Issue by JoshButton** [gotzl/ldparser#5]
Hi gotzl,

Thank you for your fantastic script. With the latest version I am getting a UnicodeDecodeError.
![image](https://user-images.githubusercontent.com/34740880/82618225-5e89a700-9bca-11ea-93af-4851d02930c6.png)

I can get around this by adding an ignore attribute to the .decode on line 407 
` return bytes.decode('ascii','ignore').strip().rstrip('\0').strip() `

Though after this fix when parsing a .ld file from a real MoTec data logger file I get the Datatype 5 not recognised error mentioned in issue #4. As was mentioned there I fixed this error by adding 0x05 to in32 at line 352 as below (not sure if this is how to fix this error properly but this seems to work):
`elif dtype_a in [0, 0x05]:`
`dtype = [None, np.int16, None, np.int32][dtype-1]`

Hope this helps with your development.

**Comment by gotzl** [comment]
Again, didn't notice the issues appearing in this project ;)
Is this still an issue with the current code basis (the ascii thing)?

**Comment by gotzl** [comment]
No feedback, closing
