### ISSUE TITLE
DiRT Rally 2.0 RDA

### ISSUE THREAD

**Issue by JoshButton** [gotzl/ldparser#6]
Hi again Gotzl,

Again I want to thank you for this fantastic script it has proven very helpful with my final year project at university. Though due to a lack of real racing I am having to turn to simulator data and as you said you only have access to data from certain simulators/loggers.

Here are 2 .ld files from DiRT Rally 2.0 captured using the tool RaceTrack Data Acquisition (RDA):
https://we.tl/t-TJuyHuUK9X 

When I decode these .ld files using ldparser I don't get the datatype 5 error like with MoTec Logger files, but all of the data comes out in a very small range and the data does not match what is seen in MoTec i2 software. I did notice the scale value for each channel is extremely large where with the MoTec logger channel scale is usually (I believe always) = 1. Apologies I have not worked this one out yet, you seem to be more knowledgeable in this area. If you would like data from other sims and loggers to test please feel free to reach out. 

Regards,
Josh

**Comment by gotzl** [comment]
Hi,
sorry for the late reply, didn't get notifications for some reason... Not sure if it's still relevant to you, but could you reup the file?
Cheers!

**Comment by gotzl** [comment]
No feedback, closing
