### ISSUE TITLE
writing

### ISSUE THREAD

**Issue by Eugenio-Pozzobon** [gotzl/ldparser#7]
I'm trying to write ld copy file using de ld write sketch inside the original code, i'm getting some errors. 

/... parse code here

if __name__ == '__main__':

    import numpy as np
    import sys, os, glob
    from itertools import groupby
    import pandas as pd

    if len(sys.argv)!=2:
        print("Usage: ldparser.py /some/path/")
        exit(1)

    for f in glob.glob('%s/*.ld'%sys.argv[1]):
        print(os.path.basename(f))

        l = ldData.fromfile(f)
        print(l.head)
        print(list(map(str, l)))
        print()
        l.write("/wdt/Sample.ld")

the error is:

Traceback (most recent call last):
  File "write ld.py", line 468, in <module>
    l.write("/wdt/Sample.ld")
  File "write ld.py", line 118, in write
    with open(f, 'wb') as f_:
FileNotFoundError: [Errno 2] No such file or directory: '/wdt/Sample.ld'

If I change the line l.write to l.write("wdt/Sample.ld") I got

Traceback (most recent call last):
  File "write ld.py", line 468, in <module>
    l.write("wdt/Sample.ld")
  File "write ld.py", line 119, in write
    self.head.write(f_, len(self.channs))
  File "write ld.py", line 294, in write
    self.aux.write(f)
  File "write ld.py", line 157, in write
    self.venue.write(f)
  File "write ld.py", line 187, in write
    self.vehicle.write(f)
  File "write ld.py", line 209, in write
    f.write(struct.pack(ldVehicle.fmt, self.id.encode(), self.weight))
struct.error: pack expected 4 items for packing (got 2)

**Comment by j-antunes** [comment]
"FileNotFoundError: [Errno 2] No such file or directory: '/wdt/Sample.ld'"

Based on the above line. I would say that the file is not in the correct directory. Make sure that the wdt folder is on the same directory where you are executing the script!

**Comment by Eugenio-Pozzobon** [comment]
i read the sample.ld at the data directory and try to write the same data values at a sample.ld in wdt directory

![image](https://user-images.githubusercontent.com/57693382/92398673-692b6600-f0ff-11ea-8786-0e8f5ae3ef7e.png)

**Comment by j-antunes** [comment]
I believe the issue is that you are putting "/wdt/Sample.ld", when you should be writing "wdt/Sample.ld"
When you want to go inside a folder from your main path, you just need to write the name of the folder. You don't nee to put the first bar "/".

Abraço

**Comment by Eugenio-Pozzobon** [comment]
Yes, i think this so, but when i try to write as you said, I get this errors:

Traceback (most recent call last):
  File "write ld.py", line 468, in <module>
    l.write("wdt/Sample.ld")
  File "write ld.py", line 119, in write
    self.head.write(f_, len(self.channs))
  File "write ld.py", line 294, in write
    self.aux.write(f)
  File "write ld.py", line 157, in write
    self.venue.write(f)
  File "write ld.py", line 187, in write
    self.vehicle.write(f)
  File "write ld.py", line 209, in write
    f.write(struct.pack(ldVehicle.fmt, self.id.encode(), self.weight))
struct.error: pack expected 4 items for packing (got 2)

**Comment by Eugenio-Pozzobon** [comment]
Update!!

This function needed to be corrected at ldVehicle class was missing some parameters:

**"self.weight, self.type.encode(), self.comment.encode()"**

    def write(self, f):
        f.write(struct.pack(ldVehicle.fmt, self.id.encode(), self.weight, self.type.encode(), self.comment.encode()))

now I'm creating a file, but with a lot of internal errors, and i'm getting this report:

 write ld.py:116: RuntimeWarning: invalid value encountered in true_divide
  conv_data = lambda c: (c.data - c.shift) * c.scale / pow(10., -c.dec)

**Comment by j-antunes** [comment]
Nice! Feel free to make a push request.

**Comment by gotzl** [comment]
Sorry for the late reply, for some reason I don't get notifications from this project. And also a small disclaimer - I never got the '.ld' write working so that i2 was able to read it ....
I'm not sure why you get the true_divide error. Probably a large value for `c.dec`, which is supposed to scale the values by order of 10ths. Can you add a print(c.dec) just before that line? Or send me your input data ....

**Comment by Eugenio-Pozzobon** [comment]
Hello! Thanks! Actually, I'm using the sample.ld that comes with i2 pro...

[Sample.zip](https://github.com/gotzl/ldparser/files/5394476/Sample.zip)
